### ISSUE TITLE
Which version of MRTK should I install exactly?

### ISSUE THREAD

**Issue by g-hirota-k** [provencher/MRTK-MagicLeap#2]
According to README.md, I need to install "development version" of MRTK.
However, the latest development version of MRTK is getting some updates like every day, but this repository is not.

As I compare the date of MRTK-Magic Leap Initial Release v0.1.0 to the date of releases of MRTK, 
I assume that I need MRTK v2.3.0 on my local. Is it correct?

By the way, thank you very much for the great work on this repo. 
This project is absolutely amazing. I showed around the demo to literally every colleague at work.

**Comment by provencher** [comment]
I just updated the readme and the project.

New dependencies are 
- MRTK V2.4.1 (2.4 should work fine, 2.4.1 should be officially released very shortly). You can get my exact commit by cloning this using the submodule.
- Unity 2019.4.3f1

**Comment by g-hirota-k** [comment]
Thank you for the information and updates to README.md.

I finally found out that I should just run MRTK-MagicLeap/External/createSymlink.sh to make the submodule assets work.
(At first, I didn't realize the script and that made me think that I need to download/import MRTK sdk manually)

Again, thank you very much for your reply, repo, and all your works!
